### ISSUE TITLE
Download and Install Script extender not working

### ISSUE THREAD

**Issue by FatSealPro** [LaughingLeader-DOS2-Mods/DivinityModManager#12]
As title says, when I click it does nothing, so tried to manually install it and now when I launch the game it gets stuck on 40%, I have terrible luck with this kind of stuff lol

**Comment by LaughingLeader** [comment]
Thanks for the report. Looks like the issue was, after the keybind rework, I forgot to connect the new download keybind with the download action.

Should be fixed now.
