### ISSUE TITLE
Requesting permissions to publish DivinityModManager on Adonis UI Expo

### ISSUE THREAD

**Issue by benruehl** [LaughingLeader-DOS2-Mods/DivinityModManager#2]
Hi,

I am the author of [Adonis UI](https://github.com/benruehl/adonis-ui) and noticed that you use the package for DivinityModManager. Recently, I released a new part of the Adonis UI website called [Adonis UI Expo](https://benruehl.github.io/adonis-ui/expo/). This page presents some applications that use Adonis UI in order to give viewers a better impression about what their UI will look like.

I would love to add a section introducing your DivinityModManager as another great example. If you agree, I will create two screenshots of the tool (light mode and dark mode) and publish them together with the package name, the author's (your) name, a short description and a link to this GitHub package. Just like it is done [here](https://benruehl.github.io/adonis-ui/expo/#Stein) already.

What do you think? :)

**Comment by LaughingLeader** [comment]
Hi there!

Thanks for all your work on Adonis UI. It's made light/dark theming support waaaay easier for sure.

Sure, feel free to use DivinityModManager as an example.

I still haven't really dug into customizing the theme colors yet, but who knows when I'll get around to that (and I'm happy with the default right now anyway, haha).

**Comment by benruehl** [comment]
Cool, thanks a lot!
Glad that you enjoy the library :)

Customizing the colors should be really easy, all documented [here](https://benruehl.github.io/adonis-ui/docs/guides/colors-and-brushes/#overriding-colors) if you are interested. Please don't hesitate to ask for help in case you need some.

Good luck with your mod manager!
