### ISSUE TITLE
Cant link to Workshop / Suggestions

### ISSUE THREAD

**Issue by TheKotU** [LaughingLeader-DOS2-Mods/DivinityModManager#3]
Hey LaughingLeader, 

First off Thanks So Much for this, i have been looking for a good mod organizer for Divinity for Such a long time, this is perfect, and much easier to use then all the other options out there - So you have already made my life easier, but i like to suggest stuff anyway feel free to implement or ignore as its your time and effort, enough of my rambling.

Bug?
1. don't know if i did not install it correctly or it just isn't working but the right click option to go to the workshop page doesn't work for me, its greyed out, so have to find it in my sub list to link to it from the workshop subs page for eg.

Suggestion

I also play and mod Kerbal Space Program and also Skyrim, using both CKAN for KErbal, and Vortex for Skyrim, they are both inspirations for my suggestion

Relations/Requirements/Rules (however you want to define them)

The ability to define rules, so that sorting the list by Rules would then make the load order more easy to make, download a mod, and its pre req, mark their relationships(or the ones i noticed when you hover over them) then solve the load order.

Manual setting of rules would be nice.

A step further (dunno how complex this would be, but conflict detection/ and if able to detect and prompt for load order rules/confirmation before running the game)

Rules could be: (should be able to have multiple rules per mod/mod-group

Load before(if grouping selected can select individual mods or a mod group (like all odinblade mods))

Load after(grouping same as above)

Never together with (incase a mod conflict badly with another, in which case will highlight and prompt the user to decide on one or the other

Library/Load before(ALL) (marks mod to load first and tops it (like selecting odincore, would automatically place it 1st or above other mods)

and for patches or overrides or mods that have to load last
Load After(ALL)

I know i have suggested a lot, but im rambling, major respect still on all your mods and efforts.

**Comment by TheKotU** [comment]
may have answered my own question, your mods work for this, i assume mod author needs to embed the link in their mod for this to work?

would it be possible to use the local workshop folder on pc to use the folder numbers as the link, if no embedded link available?

**Comment by LaughingLeader** [comment]
There's no link located in a mod's pak unfortunately. The workshop link is determined by the mod's workshop folder, if one is found for the mod's UUID. If there's no workshop folder for the mod, then it's greyed out (for now).

For the mod sorting/rule idea, I'd like to eventually implement some sort of basic sorting system, but something that should be kept in mind is that for the most part, mod order doesn't really matter, until you use mods that overwrite the same things.

Dependencies of mods will automatically be loaded before those mods, regardless of the mod order (this is a game thing). Dependencies will even be loaded if the mod exists and that dependency mod is not in the "active" list, as long as a mod depends on it.

The main thing that needs consideration in a mod order is whether multiple mods overwrite the same values - In those situations, the mods you want to "win" need to be lower in the order.

For instance, if you have an overhaul mod, but then have a mod that tweaks specific skills, chances are you'd like the latter to be after the overhaul, so those tweaks remain.

Beyond that, a simple sort function that sorts mods by perhaps workshop tags and dependencies would at least be nice to make a list more organized. Perhaps a rule / priority thing would be nice there too, like you suggested, for making mods you want to always "win" load last.

**Comment by TheKotU** [comment]
thanks for the quick reply LaughingLeader, its good that we can depend on the game to at least to handle pre req dependencies, which is nice- if the mod load order we had made was bad...or mattered more,like for kerbal or skyrim

thanks again man, gonna go back and try to break my game again and get used to your tools workings.

**Comment by LaughingLeader** [comment]
For sure. Thanks for the suggestion! I have plans for adding more workshop support, which will hopefully include being able to find a mod's workshop link without having to be subscribed to it.

Currently I have an update in the works that can at least grab a mod's workshop tags, description, last update date, etc. That's for initially being able to filter mods by tags, but then hopefully for sorting mods down the road as well (in-depth sorting can get pretty complex, so creating that system will take more time unfortunately).

**Comment by TheKotU** [comment]
found something out

as i was browsing my workshop, i found that a lot of the mods were not showing as subbed on the mod page(they were showing subscribed in the subscribed items though), even though they were in the harddrive workshop folder, and the mods folder and showing in the list of available mods in the DOS2 mod launcher and your program as well...when i subscribed to them again, it fixed the link.....dunno how that happened but its a workaround (so far resubbed to 20 mods all of them used to have grey links)....this has me confused otherwise...

**Comment by LaughingLeader** [comment]
There was a little mistake in a previous mod manager version that moved the mods from your workshop folders to your documents mods folder when updating. This was fixed recently.

So what's happening there is some of your workshop folders are empty (mods that haven't updated through Steam yet). Re-subscribing makes Steam download them again.

**Comment by TheKotU** [comment]
makes sense, as to why some of my mods were not working at all(assuming were just talking steam)...... lol will resub to all and see what it does
