### ISSUE TITLE
Inactive mods cannot be activated

### ISSUE THREAD

**Issue by brothan323** [LaughingLeader-DOS2-Mods/DivinityModManager#5]
What is with this launcher? NOTHING I add can be activated. It keeps giving me this stupid error of missing mods in mod list.

Dragging and dropping does not work. There's NO information ANYWHERE on how to fix this. The only fix is loading up the game and activating the mod there. This manager is a joke.

**Comment by LaughingLeader** [comment]
I need more information, so I can see if this is something that can be replicated on my end.

1. What version of windows are you using? (Windows 10, 7, etc).
2. Does the missing mods UI display names, or is it empty?
3. What are you doing to make the missing mods UI appear? Selecting a load order, exporting the order to the game?
4. Are you using the latest version of the mod manager?

There's no information on how to fix this, as it isn't a regular problem, or even one that has been reported, so it sounds like you've discovered a bug with your current setup, but it's hard to tell without knowing the steps you're taking to produce it.

It sounds like you may be missing a dependency mod if you're getting a warning about missing mods, but this shouldn't appear until you either export your order to the game, or load a saved order that has mods you're missing or mod dependencies you're missing.

You can disable this warning under Settings -> Preferences -> Disable Missing Mod Warnings, but the fact you're seeing it speaks to some issue with your current setup.

Example of moving mods over that are missing a dependency:
[![Missing Mods](https://thumbs.gfycat.com/ImpossiblePoorLadybug-size_restricted.gif)](https://gfycat.com/ImpossiblePoorLadybug)

**Comment by LaughingLeader** [comment]
Additionally mods with a red background are classic mods (they also have [Classic] appended to their name), and cannot be dragged to the active side, since the manager is currently only for the Definitive Edition.
