### ISSUE TITLE
Export Active Mods to zip creates a corrupted zip file

### ISSUE THREAD

**Issue by pjominet** [LaughingLeader-DOS2-Mods/DivinityModManager#6]
![Capture](https://user-images.githubusercontent.com/18309866/87350102-a9cf8e80-c557-11ea-9bee-4797d6d3882c.PNG)
 I used 7zip to extract, and it gives me the errors seen in the screenshot. Don't have more info than that :/

**Comment by LaughingLeader** [comment]
Is it still this way for you? I've been using that feature for a while and I haven't had any header errors, so there may be something else to this.
