### ISSUE TITLE
If Mods folder does not exists, nothing happens and nothing indicates this issue

### ISSUE THREAD

**Issue by WSSDude** [LaughingLeader-DOS2-Mods/DivinityModManager#7]
I didn't know what I'm doing wrong. I could not install mods with this for whatever reason, they did not want to copy it seemed. 

I then read somewhere mods should be placed in specific Mods folder location in user Documents folder. I found out I do not have this folder (fresh install from GOG, launched once). I created the folder and it finally started behaving.

I think there should be some check added if folder exists and if it does not, create it for the user to save some headaches like I had.
Or at least indicate this error somehow so new users know what is wrong at least.

**Comment by LaughingLeader** [comment]
Ah, yes, the game currently needs to be run once, as you need that so the game makes a profile as well (profiles are more than just a folder, since they have a bunch of files for option settings etc).

**Comment by WSSDude** [comment]
Problem actually is that I did this (as I mentioned before). I think this may be some weird GOG version behavior?

I freshly bought it, installed, played for like 2 hours and then started looking for some mods. So I played it for a bit, I had all other folders in place, just this one was missing for one reason or another.

When I manually created it, it started working. So problem for me at least was missing `C:\Users\%USERPROFILE%\Documents\Larian Studios\Divinity Original Sin 2 Definitive Edition\Mods` folder to be specific. MM probably failed copying into it, as it did not exist, without any warnings. It just failed and continued as usual.

I don't know how it would behave without even launching the game once, I did not try.

**Comment by LaughingLeader** [comment]
Gotcha, that makes sense. Perhaps the Steam version creates the folder automatically if you have Workshop mods subscribed, while the GoG version doesn't make this folder unless it downloads mods (which may only be when getting them through Peer-to-Peer downloading in multiplayer)?

**Comment by LaughingLeader** [comment]
Should be fixed in the next update. Thanks for letting me know.
